keys_trivial:
  - &admin  01D737F36BEBE286 

keys_home: &keys_home
  - age1fwqccrhcurtdyx9ck3q0sjvcjzrgfmyr6jhjycfjghewc65aecyqj355sd  # laptop

keys: &keys
  - age1h94rv0w2wt2rjfgnz9wuecr7skh954nps542dhuhp60yl4jqnsasv009c9  # laptop
  - age1g7cw65v67qqftkau33adyap3ffrcpgqswe95qrjxqp9uc93hnd4sn32yrl  # snailbox

creation_rules:
  - path_regex: config/secrets_uncrypted/.*
    key_groups:
      - age: *keys

  - path_regex: config/secrets_home_uncrypted/.*
    key_groups:
      - age: *keys_home

  - path_regex: config/secrets_yaml_uncrypted/.*
    key_groups:
      - age: *keys

  - pgp: *admin
