laptop: &laptop
  - &home_laptop age1n84cc8hmfnckhz2rgaq49eqvanzct56uxxdagmvtmj43zk0zvdaspgg99g
  - &sys_laptop age10nynwfurvdgnuf4yeh62gdfln2kns58pfjm5t4q2q7dg6kpmwd4qx77ydp

keys_home: &keys_home
  - *home_laptop

keys: &keys
  - *sys_laptop
  - age1xfcnkq4ynkj60adu36v6up8355vh88ea33penx3rzxsfcjua8ytsqzrxha  # snailbox

creation_rules:
  - path_regex: config/secrets_unenc/.*
    key_groups:
      - age: *keys

  - path_regex: config/secrets_home_unenc/.*
    key_groups:
      - age: *keys_home

  - path_regex: modules/*
    key_groups:
      - age: *keys
  
  - path_regex: profiles/laptop/.*
    key_groups:
      - age: *laptop