keys_trivial:
  - &admin  01D737F36BEBE286

keys_home: &keys_home
  - age1udvrvtqu3x6wyvgw0j4d5rx20k9q6c27yj8jgsfzy94t6j24r4wsd0mnvl  # laptop

keys: &keys
  - age1aer5emgezctnsu08va04xtuk73chxnqh7umls8eu69twlk7prgsq2hu2mx  # laptop
  - age1g7cw65v67qqftkau33adyap3ffrcpgqswe95qrjxqp9uc93hnd4sn32yrl  # snailbox

creation_rules:
  - path_regex: config/secrets_uncrypted/.*
    key_groups:
      - age: *keys

  - path_regex: config/secrets_home_uncrypted/.*
    key_groups:
      - age: *keys_home

  - path_regex: config/secrets_yaml_uncrypted/.*
    key_groups:
      - age: *keys

  - pgp: *admin
