# https://min.io/docs/kes/tutorials/configuration/
address: 198.18.10.6:443 # Listen on all network interfaces on port 7373

admin:
  identity: disabled # The client.crt identity

tls:
  key: /run/credentials/minio-kes.service/private.key    # The KES server TLS private key
  cert: /run/credentials/minio-kes.service/public.crt    # The KES server TLS certificate
  password: ""                     # An optional password to decrypt the TLS private key

log:
  error: on
  audit: off

policy:
  minio:
    allow:
      - /v1/key/create/minio-*
      - /v1/key/generate/minio-*
      - /v1/key/decrypt/minio-*
      - /v1/key/list/*
      - /v1/key/delete/minio-*
    identities:
      - cb879a43fc4298b57d490bc41e58f0654097afcd845086efb161b733dc1e36e0

key:
  - name: minio-default-key

keystore:
  fs:
    path: /var/lib/kes/keys
